#!/usr/bin/env bash
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
CONFIG_DIR=${WORKPULSE_SH_CONFIG_DIR:-"$HOME/.workpulse-sh"}
CONFIG_FILE=${WORKPULSE_SH_CONFIG_FILE:-"$CONFIG_DIR/config"}
VENV_DIR=${WORKPULSE_SH_VENV:-"$SCRIPT_DIR/.venv"}
RECONFIGURE=0

usage() {
  cat <<'EOF'
Usage:
  ./run.sh                 # use existing config or guide first-time setup
  ./run.sh --reconfigure   # rewrite local config
  ./run.sh --help
EOF
}

log() {
  printf '[sessionHelper bootstrap] %s\n' "$*"
}

die() {
  printf '[sessionHelper bootstrap] ERROR: %s\n' "$*" >&2
  exit 1
}

platform_name() {
  case "$(uname -s 2>/dev/null || printf unknown)" in
    Darwin) printf mac ;;
    Linux) printf linux ;;
    *) printf unknown ;;
  esac
}

install_hint() {
  name=$1
  case "$(platform_name)" in
    mac)
      case "$name" in
        python3) printf 'Install Python 3.9+ with: brew install python\n' ;;
        tmux) printf 'Install tmux with: brew install tmux\n' ;;
        *) printf 'Install and login to your AI CLI first. This launcher does not install AI CLIs.\n' ;;
      esac
      ;;
    linux)
      case "$name" in
        python3) printf 'Install Python 3.9+ with: sudo apt-get install python3 python3-venv python3-pip\n' ;;
        tmux) printf 'Install tmux with: sudo apt-get install tmux\n' ;;
        *) printf 'Install and login to your AI CLI first. This launcher does not install AI CLIs.\n' ;;
      esac
      ;;
    *)
      printf 'Install %s with your platform package manager. Windows is not supported in this release.\n' "$name"
      ;;
  esac
}

require_cmd() {
  name=$1
  if ! command -v "$name" >/dev/null 2>&1; then
    install_hint "$name" >&2
    die "missing required command: $name"
  fi
}

check_python() {
  python_bin=$1
  if ! "$python_bin" - <<'PY'
import sys
raise SystemExit(0 if sys.version_info >= (3, 9) else 1)
PY
  then
    install_hint python3 >&2
    die "python3 must be version 3.9 or newer"
  fi
}

shell_quote() {
  # Single-quote for POSIX shell config files.
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

prompt_value() {
  label=$1
  default=$2
  secret=${3:-0}
  if [ "$secret" = "1" ]; then
    if [ -n "$default" ]; then
      printf '%s [keep existing]: ' "$label" >&2
    else
      printf '%s: ' "$label" >&2
    fi
    stty -echo 2>/dev/null || true
    IFS= read -r value || value=
    stty echo 2>/dev/null || true
    printf '\n' >&2
  else
    if [ -n "$default" ]; then
      printf '%s [%s]: ' "$label" "$default" >&2
    else
      printf '%s: ' "$label" >&2
    fi
    IFS= read -r value || value=
  fi
  if [ -z "$value" ]; then
    value=$default
  fi
  printf '%s' "$value"
}

write_config() {
  old_session=${SH_SESSION_NAME:-}
  old_key=${SH_KEY_ID:-}
  old_secret=${SH_SECRET:-}
  old_cli=${SH_CLI:-claude}
  old_cli_cmd=${SH_CLI_CMD:-}
  old_cli_cwd=${SH_CLI_CWD:-$(pwd -P)}
  old_ws=${SH_WS_BASE:-ws://127.0.0.1:8791}
  old_collect=${SH_COLLECT:-1}
  old_async_reply=${SH_ASYNC_REPLY:-0}
  old_mirror=${SH_MIRROR_TO:-}
  old_target_group=${SH_TARGET_GROUP:-}
  old_target_bot=${SH_TARGET_BOT:-}
  old_producer=${SH_PRODUCER:-0}
  old_ready_timeout=${SH_CLI_READY_TIMEOUT:-90}
  old_reply_wait=${SH_CLI_REPLY_WAIT:-45}

  log "writing local config: $CONFIG_FILE"
  umask 077
  mkdir -p "$CONFIG_DIR"
  tmp="$CONFIG_FILE.tmp.$$"

  session_name=$(prompt_value "Session name (会话名)" "$old_session" 0)
  key_id=$(prompt_value "WorkPulse key_id (公开租户标识)" "$old_key" 0)
  secret=$(prompt_value "WorkPulse secret (hidden)" "$old_secret" 1)
  cli_name=$(prompt_value "AI CLI name (claude/codex/aider/cline/gemini)" "$old_cli" 0)
  cli_cmd=$(prompt_value "AI CLI command override (optional)" "$old_cli_cmd" 0)
  cli_cwd=$(prompt_value "AI CLI working directory" "$old_cli_cwd" 0)
  ws_base=$(prompt_value "WorkPulse WS base URL" "$old_ws" 0)
  collect=$(prompt_value "Collect transcript for evidence? 1=yes 0=no" "$old_collect" 0)
  mirror_to=$(prompt_value "Mirror target address (optional)" "$old_mirror" 0)
  ready_timeout=$(prompt_value "CLI ready timeout seconds" "$old_ready_timeout" 0)
  reply_wait=$(prompt_value "CLI reply wait seconds" "$old_reply_wait" 0)

  [ -n "$session_name" ] || die "session name is required"
  [ -n "$key_id" ] || die "key_id is required"
  [ -n "$secret" ] || die "secret is required"
  [ -n "$cli_name" ] || die "AI CLI name is required"
  [ -n "$cli_cwd" ] || die "AI CLI working directory is required"
  [ -n "$ws_base" ] || die "WorkPulse WS base URL is required"

  {
    printf '# WorkPulse sessionHelper local config. Permission must stay 600.\n'
    printf '# Generated by tools/sessionhelper/run.sh. Do not commit this file.\n'
    printf 'SH_SESSION_NAME=%s\n' "$(shell_quote "$session_name")"
    printf 'SH_KEY_ID=%s\n' "$(shell_quote "$key_id")"
    printf 'SH_SECRET=%s\n' "$(shell_quote "$secret")"
    printf 'SH_MODE=%s\n' "$(shell_quote cli)"
    printf 'SH_CLI=%s\n' "$(shell_quote "$cli_name")"
    printf 'SH_CLI_LAUNCH=%s\n' "$(shell_quote pty)"
    printf 'SH_CLI_CMD=%s\n' "$(shell_quote "$cli_cmd")"
    printf 'SH_CLI_CWD=%s\n' "$(shell_quote "$cli_cwd")"
    printf 'SH_CLI_READY_TIMEOUT=%s\n' "$(shell_quote "$ready_timeout")"
    printf 'SH_CLI_REPLY_WAIT=%s\n' "$(shell_quote "$reply_wait")"
    printf 'SH_WS_BASE=%s\n' "$(shell_quote "$ws_base")"
    printf 'SH_COLLECT=%s\n' "$(shell_quote "$collect")"
    printf 'SH_ASYNC_REPLY=%s\n' "$(shell_quote "$old_async_reply")"
    printf 'SH_MIRROR_TO=%s\n' "$(shell_quote "$mirror_to")"
    printf 'SH_TARGET_GROUP=%s\n' "$(shell_quote "$old_target_group")"
    printf 'SH_TARGET_BOT=%s\n' "$(shell_quote "$old_target_bot")"
    printf 'SH_PRODUCER=%s\n' "$(shell_quote "$old_producer")"
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$CONFIG_FILE"
  chmod 600 "$CONFIG_FILE"
}

load_config() {
  [ -f "$CONFIG_FILE" ] || return 1
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
  return 0
}

apply_config_defaults() {
  : "${SH_SESSION_NAME:?SH_SESSION_NAME is required in $CONFIG_FILE}"
  : "${SH_KEY_ID:?SH_KEY_ID is required in $CONFIG_FILE}"
  : "${SH_SECRET:?SH_SECRET is required in $CONFIG_FILE}"
  SH_MODE=${SH_MODE:-cli}
  SH_CLI=${SH_CLI:-claude}
  SH_CLI_LAUNCH=${SH_CLI_LAUNCH:-pty}
  SH_CLI_CMD=${SH_CLI_CMD:-}
  SH_CLI_CWD=${SH_CLI_CWD:-$(pwd -P)}
  SH_CLI_READY_TIMEOUT=${SH_CLI_READY_TIMEOUT:-90}
  SH_CLI_REPLY_WAIT=${SH_CLI_REPLY_WAIT:-45}
  SH_WS_BASE=${SH_WS_BASE:-ws://127.0.0.1:8791}
  SH_COLLECT=${SH_COLLECT:-1}
  SH_ASYNC_REPLY=${SH_ASYNC_REPLY:-0}
  SH_MIRROR_TO=${SH_MIRROR_TO:-}
  SH_TARGET_GROUP=${SH_TARGET_GROUP:-}
  SH_TARGET_BOT=${SH_TARGET_BOT:-}
  SH_PRODUCER=${SH_PRODUCER:-0}
}

ensure_secure_config() {
  [ -f "$CONFIG_FILE" ] || die "config does not exist: $CONFIG_FILE"
  perms=$(python3 - "$CONFIG_FILE" <<'PY'
import os, stat, sys
mode = stat.S_IMODE(os.stat(sys.argv[1]).st_mode)
print(oct(mode)[2:])
raise SystemExit(0 if mode == 0o600 else 1)
PY
  ) || die "config permission must be 600, got $perms. Run: chmod 600 '$CONFIG_FILE'"
}

ensure_venv() {
  python_bin=$1
  if [ ! -x "$VENV_DIR/bin/python" ]; then
    log "creating virtualenv: $VENV_DIR"
    "$python_bin" -m venv "$VENV_DIR" || die "failed to create venv. On Linux install python3-venv."
  fi
  log "installing Python dependencies in isolated venv"
  "$VENV_DIR/bin/python" -m pip install -q --upgrade pip
  "$VENV_DIR/bin/python" -m pip install -q -r "$SCRIPT_DIR/requirements.txt"
}

detect_cli_command() {
  if [ -n "${SH_CLI_CMD:-}" ]; then
    # Extract the first shell word portably through Python shlex.
    "$VENV_DIR/bin/python" - "$SH_CLI_CMD" <<'PY'
import shlex, sys
parts = shlex.split(sys.argv[1])
print(parts[0] if parts else "")
PY
    return
  fi
  printf '%s' "${SH_CLI:-claude}"
}

tmux_session_name() {
  "$VENV_DIR/bin/python" - "$SH_SESSION_NAME" "$SH_KEY_ID" <<'PY'
import re, sys
session_name, key_id = sys.argv[1], sys.argv[2]
base = re.sub(r"[^A-Za-z0-9_-]+", "-", session_name or "session").strip("-") or "session"
suffix = re.sub(r"[^A-Za-z0-9_-]+", "", key_id or "")[-8:] or "local"
print(("sh-" + base + "-" + suffix)[:80])
PY
}

cleanup_tmux() {
  if [ "${SH_CLI_LAUNCH:-pty}" = "tmux" ] && command -v tmux >/dev/null 2>&1 && [ -n "${SH_SESSION_NAME:-}" ] && [ -n "${SH_KEY_ID:-}" ] && [ -x "$VENV_DIR/bin/python" ]; then
    session=$(tmux_session_name 2>/dev/null || true)
    if [ -n "$session" ]; then
      tmux kill-session -t "$session" >/dev/null 2>&1 || true
    fi
  fi
}

for arg in "$@"; do
  case "$arg" in
    --reconfigure) RECONFIGURE=1 ;;
    --help|-h) usage; exit 0 ;;
    *) usage; die "unknown argument: $arg" ;;
  esac
done

case "$(platform_name)" in
  mac|linux) ;;
  *) die "unsupported platform. R10 supports Linux and Mac only." ;;
esac

require_cmd python3
check_python python3

if [ "$RECONFIGURE" = "1" ] && [ -f "$CONFIG_FILE" ]; then
  load_config || true
fi
if [ "$RECONFIGURE" = "1" ] || [ ! -f "$CONFIG_FILE" ]; then
  write_config
fi
load_config || die "failed to load config: $CONFIG_FILE"
apply_config_defaults
ensure_secure_config
ensure_venv python3

cli_cmd=$(detect_cli_command)
[ -n "$cli_cmd" ] || die "AI CLI command is empty"
if ! command -v "$cli_cmd" >/dev/null 2>&1; then
  install_hint "$cli_cmd" >&2
  die "missing AI CLI command: $cli_cmd"
fi

PYTHONPATH="$SCRIPT_DIR${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONPATH
# 导出所有 SH_* 变量(含 SH_DEBUG/SH_OPEN_TIMEOUT 等,以后新增不会再漏)
for _shvar in ${!SH_*}; do export "$_shvar"; done
log "starting sessionHelper session=$SH_SESSION_NAME key_id=$SH_KEY_ID cli=$SH_CLI ws=$SH_WS_BASE"
log "secret loaded from local config; it will not be printed"
trap cleanup_tmux EXIT
"$VENV_DIR/bin/python" -m sessionhelper
